#!/bin/bash
########################################################################################

# helper functions:
###################

# $1: Metadata file
get_headers() {
    awk -F ':' '/^key:/ {print $2}' "$1" | paste -s -d ":" -
}

# $1: Metadata File
# $2: flag='noID'
columns_menu() {
    local meta_file="$1"
    headers=$(get_headers "$meta_file")
    num_cols=$(echo "$headers" | tr ':' '\n' | wc -l)

    echo "Select a column:"
    if [[ $2 != 'noID' ]]; then
        echo "$headers" | tr ':' '\n' | nl -w 1 -s ") "
    else
        echo "$headers" | cut -d ':' -f2- | tr ':' '\n' | nl -w 1 -s ") "
        ((num_cols--))
    fi

    echo
    clear_buffer
    read -r -p "Enter column number: " col_choice

    if ! is_int "$col_choice" || [[ $col_choice -lt 1 || $col_choice -gt $num_cols ]]; then
        unset col_choice col_name
        echo "Invalid choice!"
        return 1
    fi

    [[ $2 == 'noID' ]] && ((col_choice++))
    col_name=$(echo "$headers" | cut -d ':' -f$((col_choice)))
    return 0
}

validate_input() {
    local field="$1"
    local type="$2"
    local constraints="$3"
    local msg="$4"

    # Find column index from the header of the table file
    # need to escape $field
    col_index=$(awk -F ":" -v field="$field" '
        NR==1 {
            for (i=1; i<=NF; i++) {
                if ($i == field) {
                    print i;
                    exit;
                }
            }
        }' "$table_file")

    if [[ -z "$col_index" ]]; then
        echo "❌ Error: Column '$field' not found in the table."
        return 1
    fi

    while :; do
        echo
        clear_buffer
        read -r -p "$msg" value && value=$(trim_tolower "$value")
        [[ "$value" == "n/a" ]] && value=""
        [[ "$value" == "/" ]] && return 1

        # Check PK constraint (must be unique and not null)
        [[ "$constraints" == *"pk"* ]] && {
            [[ -z "$value" ]] && echo "Error: '$field' (Primary Key) cannot be empty!" && continue
            if [[ "$constraints" == *"unique"* ]]; then
                # need to escape $value
                if awk -F ":" -v col="$col_index" -v val="$value" 'NR > 1 && $col == val {exit 1}' "$table_file"; then
                    echo "Error: '$field' (Primary Key) must be unique!"
                    continue
                fi
            fi
        }

        # Check NOT NULL constraint
        [[ "$constraints" == *"notnull"* && -z "$value" ]] && echo "Error: '$field' cannot be empty." && continue

        # Check UNIQUE constraint (if not a PK)
        if [[ "$constraints" == *"unique"* ]]; then
            # need to escape $value
            if ! awk -F ":" -v col="$col_index" -v val="$value" '
                NR > 1 {
                    if ($col == val) {
                        exit 1;
                    }
                }' "$table_file"; then
                echo "Error: This '$field' already exists. Please enter a different value."
                continue

            fi
        fi

        if [[ -n "$value" ]]; then
            case "$type" in
            "str")
                if ! is_str "$value"; then
                    echo "Error: '$field' must start with letter and cannot contain ':'."
                    continue
                fi
                ;;
            "int")
                if ! is_int "$value"; then
                    echo "Error: '$field' must be an integer."
                    continue
                fi
                ;;
            "email")
                if ! is_email "$value"; then
                    echo "Error: Invalid email format you must enter in this format: 'john@example.com'"
                    continue
                fi
                ;;
            "phone")
                if ! is_phone "$value"; then
                    echo "Error: Invalid phone format. Must be egyption number 'ex: 010-xxx-xxx-xx' digits."
                    continue
                fi
                ;;
            *)
                echo "Error: Unknown type '$type' for '$field'."
                continue
                ;;
            esac
        fi

        # Assign reply value
        [[ -n "$value" ]] && reply="$value" || reply="N/A"
        return 0
    done
}

# $3: 'insert', 'update'
new_record() {
    local meta_file="$1"
    local table_file="$2"
    local column_order=()
    local -A field rules
    new_row=""

    clear_buffer
    while IFS=: read -r key name type constraints; do
        if [[ "$key" == "key" ]]; then
            field["$name"]="$type"
            rules["$name"]="$constraints"
            column_order+=("$name")
        fi
    done < <(grep '^key:' "$meta_file")

    [[ "${field["ID"]}" == "auto" ]] && attributes=("${column_order[@]:1}") || attributes=("${column_order[@]}")

    for attr in "${attributes[@]}"; do
        type="${field[$attr]}"
        constraints="${rules[$attr]}"
        [[ "$constraints" =~ notnull ]] && msg="Enter '$attr' value [$type] (cannot be empty): " || msg="Enter '$attr' value [$type] (press enter for empty value): "
        validate_input "$attr" "$type" "$constraints" "$msg"
        [[ $? -ne 0 ]] && return 1
        new_row+="$reply:"
    done

    if [[ "${field["ID"]}" == "auto" ]]; then
        [[ "$3" == 'insert' ]] && local req_id=$(awk -F ':' 'END { print $1 }' "$table_file") && ((req_id++))
        [[ "$3" == 'update' ]] && local req_id=$pk_value
        new_row="$req_id:$new_row"
    fi
    return 0
}

########################################################################################

insert_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record insertion wizard!"
    echo "*****************************************"

    echo "Enter '/' to cancel insertion:"
    new_record "$meta_file" "$table_file" "insert"
    [[ $? -ne 0 ]] && echo -e "\nInsertion cancled" && return 1
    echo "$new_row" >>"$table_file"

    row_num=$(awk -F ":" -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1")
    sed -i "${rows_md}s/^rows:[0-9]*/rows:$((++row_num))/" "$meta_file"
    sed -i "${updated_at_md}s/^updated_at:.*/updated_at:$(date)/" "$meta_file"

    echo "user '$user' inserted rows into Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/users/$user"
    echo "user '$user' inserted rows into Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/tables/$(basename "$db_path")/$(basename "$2")"
    echo -e "\nRow inserted successfully!"
    return 0
}

update_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record/s update wizard!"
    echo "*****************************************"

    read -r -p "Enter the value of the record's primary key you want to update: " pk_value && pk_value=$(trim_tolower $pk_value)

    local pk_field=$(awk -F ":" '/^pk/ {print $3}' "$meta_file") && [[ $pk_field -eq 0 ]] && ((pk_field++))
    # need to escape $pk_value and $pk_field
    local updated_line=$(awk -F ":" -v field="$pk_field" -v value="$pk_value" 'NR > 1 && $field == value { print NR; exit 0 }' "$table_file")

    [[ -z $updated_line ]] && {
        echo -e "\nError: No matching record found."
        return 1
    }

    echo "Enter '/' to cancel update:"
    new_record "$meta_file" "$table_file" "update"
    [[ $? -ne 0 ]] && echo -e "\nUpdating cancled" && return 1

    clear_buffer
    read -r -n 1 -p "Are you sure you want to update this record? (y/Y) " confirmation
    [[ "$confirmation" != [Yy] ]] && {
        echo -e "\nUpdating canceled."
        return 1
    }

    # need to escape $new_row properly
    new_row=$(echo "$new_row" | sed 's/\\/\\\\/g')
    sed -i "${updated_line}s/.*/$new_row/" "$table_file"

    echo "user '$user' updated a row in Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/users/$user"
    echo "user '$user' updated a row in Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/tables/$(basename "$db_path")/$(basename "$2")"
    echo -e "\nRecord(s) updated successfully!"
    return 0
}

replace_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record/s replace wizard!"
    echo "*****************************************"

    clear_buffer
    headers=$(get_headers "$meta_file")
    if [[ "$headers" =~ ^ID ]]; then
        columns_menu "$meta_file" 'noID'
    else
        columns_menu "$meta_file"
    fi

    [[ $? -eq 1 ]] && return 1

    clear_buffer
    read -r -p "Enter the value to replace: " old_value && old_value=$(trim_tolower "$old_value")
    [[ -z "$old_value" ]] && old_value="N/A"

    local matching_rec=$(awk -F ':' -v idx="$col_choice" -v val="$old_value" 'NR>1 && $idx == val' "$table_file")

    local matching_count=$([[ -n "$matching_rec" ]] && echo "$matching_rec" | wc -l || echo 0)
    [[ "$matching_count" -eq 0 ]] && {
        echo -e "\nError: No matching records found."
        return 1
    }

    # need to escape $col_name
    local field_type=$(awk -F ":" -v key="$col_name" '$1 == "key" && $2 == key {print $3}' "$meta_file") && field_type=$(echo "$field_type" | tr -d '\n')
    local field_constraints=$(awk -F ":" -v key="$col_name" '$1 == "key" && $2 == key {print $4}' "$meta_file") && field_constraints=$(echo "$field_constraints" | tr -d '\n')

    [[ $constraints =~ notnull ]] && msg="Enter '$col_name' value [$field_type] (cannot be empty): " || msg="Enter '$col_name' value [$field_type] (press enter for empty value): "

    validate_input "$col_name" "$field_type" "$field_constraints" "$msg"
    [[ $? -eq 0 ]] && new_value="$reply"

    clear_buffer
    read -r -n 1 -p "Are you sure you want to replace values in $matching_count record(s)? (y/Y) " confirmation
    [[ "$confirmation" != [Yy] ]] && {
        echo -e "\nUpdating canceled."
        return 1
    }
    # need to escape $new_value properly
    new_value=$(echo "$new_value" | sed 's/\\/\\\\/g')

    # need to escape $col_name and $old_value
    awk -F ':' -v idx="$col_choice" -v old_val="$old_value" -v new_val="$new_value" '
       BEGIN { OFS = ":" }
       NR == 1 { print; next }
       {
         if ($idx == old_val) {
             $idx = new_val
         }
         print
       }
    ' "$table_file" >temp_file && mv temp_file "$table_file"

    sed -i "/^updated_at:/s/.*/updated_at: $(date)/" "$meta_file"

    echo "user '$user' replaced values in Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/users/$user"
    echo "user '$user' replaced values in Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/tables/$(basename "$db_path")/$(basename "$2")"
    echo -e "\nRecord(s) updated successfully!"
    return 0
}

delete_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record deletion wizard!"
    echo "*****************************************"

    find_record "$table_file" "$meta_file"
    [[ $? -ne 0 ]] && return 1

    echo "*****************************************"
    clear_buffer
    read -r -n 1 -p "Are you sure you want to delete $matching_count record(s)? (y/Y) " confirmation
    [[ "$confirmation" != [Yy] ]] && {
        echo -e "\nDeletion canceled."
        return 1
    }

    # need to escape $value
    awk -F ':' -v idx="$col_choice" -v val="$value" '
    BEGIN { OFS = ":" }
    $idx != val { print }
    ' "$table_file" >temp_file && mv temp_file "$table_file"

    row_num=$(($(awk -F ":" -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1") - $matching_count))
    sed -i "${rows_md}s/^rows:[0-9]*/rows:$row_num/" "$meta_file"
    sed -i "${updated_at_md}s/^updated_at:.*/updated_at:$(date)/" "$meta_file"

    echo "user '$user' deleted rows from Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/users/$user"
    echo "user '$user' deleted rows from Table '$(basename "$2")' in Database '$(basename "$db_path")' at $(date)" >>"$logs_path/tables/$(basename "$db_path")/$(basename "$2")"
    echo -e "\nRecord(s) deleted successfully!"
    return 0
}

# $1: Table Data File
# $2: Meta Data File
find_record() {
    local table_file="$1"
    local meta_file="$2"

    clear
    echo "Welcome to the Find wizard!"
    echo "*****************************************"

    clear_buffer
    columns_menu "$meta_file"
    [[ $? -ne 0 ]] && return 1

    clear_buffer
    read -r -p "Enter the value: " value && value=$(trim_tolower "$value")
    [[ -z "$value" ]] && value="N/A"

    # Make `matching_rec` and `matching_count` global
    # need to escape $value properly
    escaped_value=$(echo "$value" | sed 's/[\/&]/\\&/g')
    matching_rec=$(sed '1d' "$table_file" | sed -n "/^\([^:]*:\)\{$((col_choice - 1))\}$escaped_value:/p")
    matching_count=$([[ -n "$matching_rec" ]] && echo "$matching_rec" | wc -l || echo 0)

    [[ "$matching_count" -eq 0 ]] && {
        echo -e "\nError: No matching records found."
        return 1
    }

    clear
    echo "Matching record(s):"
    echo "*****************************************"
    {
        sed -n '1p' "$table_file"
        echo "$matching_rec"
    } | column -t -s ':'
    return 0
}

show_all_records() {
    local table_file="$1"
    clear
    [[ $(wc -l <"$table_file") -gt 1 ]] && column -t -s ':' "$table_file" && return 0
    echo "No records found." && return 1
}
