#!/bin/bash
########################################################################################
# valid DataTypes
validDataTypes=("int" "str" "email" "phone" "date")

# $1: DataType to check if valid
is_type() {
    [[ " ${validDataTypes[*]} " == *" $1 "* ]]
}

# $1: value to check if integer
is_int() {
    [[ "$1" =~ ^-?[0-9]+$ ]]
}

# $1: value to check if start with letter and does not contain ':'
is_str() {
    [[ "$1" =~ ^[a-z][^:]*$ ]]
}

# $1: value to check if email
is_email() {
    [[ "$1" =~ ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$ ]]
}

# $1: value to check if phone
is_phone() {
    [[ "$1" =~ ^(01[0125])[0-9]{8}$ ]]
}

# $1: value to check if date
is_date() {
    date -d "$1" "+%Y-%m-%d" 2>/dev/null
}

# $1: value to check if does not start with '.' and does not contain ':' or '/'
is_valid_name() {
    [[ ! "$1" =~ ^\. && ! "$1" =~ [:/] ]]
}
